// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StickyChristmas
{
    internal sealed partial class Vsix
    {
        public const string Id = "846a4ff2-2fc1-4bca-861a-ecc3c0f02eba";
        public const string Name = "Sticky Christmas";
        public const string Description = @"A simulation of what happens when you spill cookies and eggnog into your keyboard while coding";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "xmas, christmas, sticky, keyboards";
    }
}
